# Generated by Django 5.0.3 on 2024-03-29 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='files/', verbose_name='Сам файл')),
                ('size', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Размер файла')),
                ('data_created', models.PositiveBigIntegerField(verbose_name='Дата создания')),
                ('date_download', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Дата крайнего скачивания')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
