# Generated by Django 5.0.3 on 2024-04-09 14:19

import mycloud.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud', '0002_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=mycloud.utils.user_directory_path, verbose_name='Сам файл'),
        ),
    ]
