# Generated by Django 5.0.3 on 2024-04-10 11:43

import django.db.models.deletion
import mycloud.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud', '0003_alter_file_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='file',
            name='data_created',
            field=models.PositiveBigIntegerField(default=mycloud.utils.seconds_since_epoch, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(default=mycloud.utils.generating_uuid, max_length=255, unique=True, verbose_name='Название файла в хэш виде'),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Размер файла, байт'),
        ),
    ]
